/**
 * Seed del catálogo global de conceptos SOS.
 * Inserta o actualiza todos los conceptos SOS conocidos en la tabla `conceptos_completos_sos`.
 *
 * Uso:
 *   bun run src/scripts/seed-conceptos-sos-catalog.ts
 *   bun run src/scripts/seed-conceptos-sos-catalog.ts --dry-run
 */
import 'dotenv/config';
import { db } from '@/lib/db';
import { conceptosCompletosSos as payrollConceptosSosCatalog } from '@/drizzle/schema';
import { eq } from 'drizzle-orm';

const DRY_RUN = process.argv.includes('--dry-run');

type ConceptoSos = {
  numeroSos: number;
  codigoAfip: string;
  nombre: string;
  tieneMemo: boolean;
  tieneCantidad: boolean;
  tienePct: boolean;
  tieneImpConceptoNro: boolean;
  tieneImporte: boolean;
  tieneImpMin: boolean;
  tieneImpMax: boolean;
  baseColumna:
    | 'valHora'
    | 'sueldoLegajo'
    | 'sueldo'
    | 'sub1_9'
    | 'sub1_19'
    | 'sub1_26'
    | 'sub1_39'
    | 'sub1_199'
    | 'sub411_469'
    | 'sub1_199_plus_411_469'
    | 'importe_fijo'
    | 'ref_concepto';
  divHsNorm: number;
  divCantidad: number;
};

// prettier-ignore
const CONCEPTOS: ConceptoSos[] = [
  { numeroSos: 1,   codigoAfip: '110000', nombre: 'Sueldo Basico',                                           tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sueldo',      divHsNorm: 1,   divCantidad: 30 },
  { numeroSos: 3,   codigoAfip: '160001', nombre: 'Antiguedad (%)',                                          tieneMemo: false, tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_9',      divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 4,   codigoAfip: '160001', nombre: 'Antiguedad (Importe)',                                    tieneMemo: false, tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 5,   codigoAfip: '170000', nombre: 'Premio',                                                  tieneMemo: false, tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 6,   codigoAfip: '110005', nombre: 'Licencias',                                               tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 7,   codigoAfip: '161000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 8,   codigoAfip: '161000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 9,   codigoAfip: '170000', nombre: 'Asignacion Complementaria (s/sueldo)',                    tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sueldo',      divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 10,  codigoAfip: '110007', nombre: 'Feriados',                                                tieneMemo: false, tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sueldo',      divHsNorm: 1,   divCantidad: 25 },
  { numeroSos: 11,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 12,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 13,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 14,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 15,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 16,  codigoAfip: '140000', nombre: 'Plus por Zona Desfavorable',                              tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 17,  codigoAfip: '130001', nombre: 'Horas extras 50% (s/valor hora)',                         tieneMemo: false, tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'valHora',     divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 18,  codigoAfip: '130002', nombre: 'Horas extras 100% (s/valor hora)',                        tieneMemo: false, tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'valHora',     divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 19,  codigoAfip: '170000', nombre: 'Asignacion Complementaria (s/conc. 1 a 9)',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_9',      divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 20,  codigoAfip: '170000', nombre: 'Asignacion Complementaria (s/conc. 1 a 9)',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_9',      divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 21,  codigoAfip: '130001', nombre: 'Horas extras 50% (s/sueldo)',                             tieneMemo: false, tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sueldo',      divHsNorm: 180, divCantidad: 1  },
  { numeroSos: 22,  codigoAfip: '130002', nombre: 'Horas extras 100% (s/sueldo)',                            tieneMemo: false, tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sueldo',      divHsNorm: 180, divCantidad: 1  },
  { numeroSos: 23,  codigoAfip: '130001', nombre: 'Horas extras 50% (s/conc. 1 a 9)',                        tieneMemo: false, tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_9',      divHsNorm: 180, divCantidad: 1  },
  { numeroSos: 24,  codigoAfip: '130002', nombre: 'Horas extras 100% (s/conc. 1 a 9)',                       tieneMemo: false, tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_9',      divHsNorm: 180, divCantidad: 1  },
  { numeroSos: 25,  codigoAfip: '130001', nombre: 'Horas extras 50% (s/conc. 1 a 19)',                       tieneMemo: false, tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_19',     divHsNorm: 180, divCantidad: 1  },
  { numeroSos: 26,  codigoAfip: '130002', nombre: 'Horas extras 100% (s/conc. 1 a 19)',                      tieneMemo: false, tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_19',     divHsNorm: 180, divCantidad: 1  },
  { numeroSos: 27,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 28,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 29,  codigoAfip: '170000', nombre: 'Asignacion Complementaria (s/conc. 1 a 19)',              tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_19',     divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 30,  codigoAfip: '170000', nombre: 'Asignacion Complementaria (s/conc. 1 a 26)',              tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_26',     divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 31,  codigoAfip: '110000', nombre: 'Ajustes de Haberes Remunerativos',                        tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 32,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 33,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 34,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 35,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 36,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 37,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 38,  codigoAfip: '110011', nombre: 'Incremento Solidario Dec.14/2020',                        tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 39,  codigoAfip: '110011', nombre: 'Incr.Salarial Dto 14/2020 Rectif',                        tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 40,  codigoAfip: '170000', nombre: 'Premio',                                                  tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 41,  codigoAfip: '120000', nombre: 'Sueldo Anual Complementario',                             tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sueldo',      divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 42,  codigoAfip: '120003', nombre: 'Sueldo Anual Complementario Proporcional',                tieneMemo: false, tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: true,  tieneImpMax: false, baseColumna: 'sueldo',      divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 43,  codigoAfip: '170000', nombre: 'Asignacion Complementaria (s/conc. 1 a 39)',              tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_39',     divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 51,  codigoAfip: '151000', nombre: 'Vacaciones Gozadas',                                      tieneMemo: true,  tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sueldo',      divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 61,  codigoAfip: '170003', nombre: 'Comisiones',                                              tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 62,  codigoAfip: '170003', nombre: 'Comisiones',                                              tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 63,  codigoAfip: '170005', nombre: 'Viaticos',                                                tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 64,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 65,  codigoAfip: '110000', nombre: 'Otros Haberes Remunerativos',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 71,  codigoAfip: '110000', nombre: 'Anticipo de Haberes',                                     tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 72,  codigoAfip: '110007', nombre: 'Feriados',                                                tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 81,  codigoAfip: '110008', nombre: 'Prest. Dineraria Ley 24577 (primeros 10d)',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 82,  codigoAfip: '110009', nombre: 'Prest. Dineraria Ley 24577 (a cargo de la ART)',          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 90,  codigoAfip: '180000', nombre: 'Rectificativa por remuneracion Ley 27.742',               tieneMemo: false, tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 101, codigoAfip: '110000', nombre: 'Dias Enfermedad',                                         tieneMemo: false, tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sueldo',      divHsNorm: 1,   divCantidad: 30 },
  { numeroSos: 102, codigoAfip: '110008', nombre: 'Dias Accidente',                                          tieneMemo: false, tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sueldo',      divHsNorm: 1,   divCantidad: 30 },
  { numeroSos: 103, codigoAfip: '110000', nombre: 'Dias Faltas Injustificadas',                               tieneMemo: false, tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sueldo',      divHsNorm: 1,   divCantidad: 30 },
  { numeroSos: 104, codigoAfip: '110007', nombre: 'Dias Feriados',                                           tieneMemo: false, tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sueldo',      divHsNorm: 1,   divCantidad: 30 },
  { numeroSos: 105, codigoAfip: '110000', nombre: 'Otros Descuentos de Haberes sobre sueldo',                tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 106, codigoAfip: '110000', nombre: 'Otros Descuentos de Haberes sobre sueldo',                tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 107, codigoAfip: '110000', nombre: 'Otros Descuentos de Haberes sobre sueldo',                tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 108, codigoAfip: '110000', nombre: 'Otros Descuentos de Haberes sobre sueldo',                tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 109, codigoAfip: '110000', nombre: 'Otros Descuentos de Haberes sobre sueldo',                tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 110, codigoAfip: '110000', nombre: 'Otros Descuentos de Haberes sobre sueldo',                tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 111, codigoAfip: '160000', nombre: 'Otros Descuentos de haberes sobre adicionales',           tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 112, codigoAfip: '160000', nombre: 'Otros Descuentos de haberes sobre adicionales',           tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 113, codigoAfip: '160000', nombre: 'Otros Descuentos de haberes sobre adicionales',           tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 114, codigoAfip: '160000', nombre: 'Otros Descuentos de haberes sobre adicionales',           tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 115, codigoAfip: '160000', nombre: 'Otros Descuentos de haberes sobre adicionales',           tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 116, codigoAfip: '160000', nombre: 'Otros Descuentos de haberes sobre adicionales',           tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 117, codigoAfip: '160000', nombre: 'Otros Descuentos de haberes sobre adicionales',           tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 118, codigoAfip: '160000', nombre: 'Otros Descuentos de haberes sobre adicionales',           tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 119, codigoAfip: '160000', nombre: 'Otros Descuentos de haberes sobre adicionales',           tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 120, codigoAfip: '160000', nombre: 'Otros Descuentos de haberes sobre adicionales',           tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 121, codigoAfip: '170000', nombre: 'Otros Descuentos de haberes sobre premios',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 122, codigoAfip: '170000', nombre: 'Otros Descuentos de haberes sobre premios',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 123, codigoAfip: '170000', nombre: 'Otros Descuentos de haberes sobre premios',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 124, codigoAfip: '170000', nombre: 'Otros Descuentos de haberes sobre premios',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 125, codigoAfip: '170000', nombre: 'Otros Descuentos de haberes sobre premios',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 126, codigoAfip: '170000', nombre: 'Otros Descuentos de haberes sobre premios',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 127, codigoAfip: '170000', nombre: 'Otros Descuentos de haberes sobre premios',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 128, codigoAfip: '170000', nombre: 'Otros Descuentos de haberes sobre premios',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 129, codigoAfip: '170000', nombre: 'Otros Descuentos de haberes sobre premios',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 130, codigoAfip: '170000', nombre: 'Otros Descuentos de haberes sobre premios',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 201, codigoAfip: '810000', nombre: 'Jubilacion',                                              tieneMemo: false, tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: true,  tieneImpMax: true,  baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 202, codigoAfip: '810001', nombre: 'Ley 19032',                                               tieneMemo: false, tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: true,  tieneImpMax: true,  baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 203, codigoAfip: '810002', nombre: 'Obra Social',                                             tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: true,  tieneImpMax: true,  baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 204, codigoAfip: '810009', nombre: 'Obra Social Adherente',                                   tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: true,  tieneImpMax: true,  baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 205, codigoAfip: '810003', nombre: 'Anssal',                                                  tieneMemo: false, tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: true,  tieneImpMax: true,  baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 206, codigoAfip: '810004', nombre: 'Sindicato',                                               tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: true,  tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 207, codigoAfip: '821000', nombre: 'Federaciones y Otros',                                    tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: true,  tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 208, codigoAfip: '810008', nombre: 'Impuesto a las Ganancias',                                tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 209, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 210, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 211, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 212, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 213, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 214, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 215, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 216, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 217, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 218, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 219, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 220, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 221, codigoAfip: '810002', nombre: 'Aporte Adicional OS',                                     tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 222, codigoAfip: '810002', nombre: 'Aporte Adicional OS',                                     tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199',    divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 223, codigoAfip: '810012', nombre: 'Salario Complementario Dec 332/2020',                     tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 226, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 227, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 228, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 229, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 230, codigoAfip: '821000', nombre: 'Otros Conceptos de Retenciones',                          tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 231, codigoAfip: '820000', nombre: 'Adelantos de sueldo',                                     tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 232, codigoAfip: '810006', nombre: 'RENATEA',                                                 tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: true,  tieneImpMax: true,  baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 233, codigoAfip: '810005', nombre: 'Seguro de Vida',                                          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: true,  tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 234, codigoAfip: '810014', nombre: 'Pago a cuenta Asignacion Puente al Empleo',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 401, codigoAfip: '520012', nombre: 'Vacaciones no Gozadas',                                   tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 402, codigoAfip: '520018', nombre: 'S.A.C. s/ Vacaciones no Gozadas',                         tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 403, codigoAfip: '520015', nombre: 'Preaviso',                                                tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 404, codigoAfip: '520011', nombre: 'Indemnizacion',                                           tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 405, codigoAfip: '520010', nombre: 'Gratificacion',                                           tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 406, codigoAfip: '520014', nombre: 'Indemnizacion por despido',                               tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 407, codigoAfip: '520016', nombre: 'Integracion Mes Despido',                                 tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 408, codigoAfip: '520017', nombre: 'SAC s/ Integracion o Preaviso',                           tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 411, codigoAfip: '540000', nombre: 'Otros Conceptos no Remunerativos c/Ap y Cont. OS',        tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 412, codigoAfip: '541000', nombre: 'Otros Conceptos no Remunerativos c/Ap y Cont. OS',        tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 413, codigoAfip: '540000', nombre: 'Otros Conceptos no Remunerativos c/Ap y Cont. OS',        tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 414, codigoAfip: '541000', nombre: 'Otros Conceptos no Remunerativos c/Ap y Cont. OS',        tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 415, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 416, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 417, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 418, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 419, codigoAfip: '550000', nombre: 'Suspension per. parc art 223 bis LCT / Res.397/20',       tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 420, codigoAfip: '110000', nombre: 'Suspension art 223 bis LCT / Res. 397/20 MTEySS',         tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 421, codigoAfip: '110000', nombre: 'Rem. habitual Dec 792/2020',                              tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 422, codigoAfip: '551002', nombre: 'Otros Conceptos No Remun c/Ap Rem 1, 4, 5, 8 y 9',       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 423, codigoAfip: '551002', nombre: 'Otros Conceptos No Remun c/Ap Rem 1, 4, 5, 8 y 9',       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 424, codigoAfip: '551002', nombre: 'Otros Conceptos No Remun c/Ap Rem 1, 4, 5, 8 y 9',       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 425, codigoAfip: '551002', nombre: 'Otros Conceptos No Remun c/Ap Rem 1, 4, 5, 8 y 9',       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 426, codigoAfip: '551002', nombre: 'Otros Conceptos No Remun c/Ap Rem 1, 4, 5, 8 y 9',       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 427, codigoAfip: '551002', nombre: 'Otros Conceptos No Remun c/Ap Rem 1, 4, 5, 8 y 9',       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 428, codigoAfip: '551002', nombre: 'Otros Conceptos No Remun c/Ap Rem 1, 4, 5, 8 y 9',       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 429, codigoAfip: '551002', nombre: 'Otros Conceptos No Remun c/Ap Rem 1, 4, 5, 8 y 9',       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 430, codigoAfip: '560001B', nombre: 'SAC No Remunerativo (Rem 4 y 8)',                        tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 431, codigoAfip: '560002B', nombre: 'SAC No Remunerativo Prop. (Rem 4 y 8)',                  tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 432, codigoAfip: '560003B', nombre: 'Vacaciones No Remunerativo (Rem 4 y 8)',                 tieneMemo: true,  tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 433, codigoAfip: '560001C', nombre: 'SAC No Remunerativo (Rem 1, 4, 5, 8, 9)',               tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 434, codigoAfip: '560002C', nombre: 'SAC No Remunerativo Prop. (Rem 1, 4, 5, 8 y 9)',        tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 435, codigoAfip: '560003C', nombre: 'Vacaciones No Remunerativo (Rem 1, 4, 5, 8 y 9)',       tieneMemo: true,  tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 436, codigoAfip: '560001D', nombre: 'SAC No Remunerativo (Rem 4, 8 y 9)',                     tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 437, codigoAfip: '560002D', nombre: 'SAC No Remunerativo Prop. (Rem 4, 8 y 9)',               tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 438, codigoAfip: '560003D', nombre: 'Vacaciones No Remunerativo (Rem 4, 8 y 9)',              tieneMemo: true,  tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 439, codigoAfip: '540000', nombre: 'Otros Conceptos no Remunerativos c/Ap y Cont. OS',        tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 440, codigoAfip: '540000', nombre: 'Otros Conceptos no Remunerativos c/Ap y Cont. OS',        tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 451, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 452, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 453, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 454, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 455, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 456, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 457, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 458, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 460, codigoAfip: '550000', nombre: 'Otros Conceptos no Rem. c/Ret OS y ART',                  tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 461, codigoAfip: '550000', nombre: 'Otros Conceptos no Rem. c/Ret OS y ART',                  tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 462, codigoAfip: '550000', nombre: 'Otros Conceptos no Rem. c/Ret OS y ART',                  tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 463, codigoAfip: '550000', nombre: 'Otros Conceptos no Rem. c/Ret OS y ART',                  tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 464, codigoAfip: '550000', nombre: 'Otros Conceptos no Rem. c/Ret OS y ART',                  tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 465, codigoAfip: '550000', nombre: 'Otros Conceptos no Rem. c/Ret OS y ART',                  tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 466, codigoAfip: '550000', nombre: 'Otros Conceptos no Rem. c/Ret OS y ART',                  tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 467, codigoAfip: '550000', nombre: 'Otros Conceptos no Rem. c/Ret OS y ART',                  tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 468, codigoAfip: '550000', nombre: 'Otros Conceptos no Rem. c/Ret OS y ART',                  tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 469, codigoAfip: '550000', nombre: 'Otros Conceptos no Rem. c/Ret OS y ART',                  tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 470, codigoAfip: '551001', nombre: 'Otros Conceptos no Rem. c/Ret ART',                       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 471, codigoAfip: '551001', nombre: 'Otros Conceptos no Rem. c/Ret ART',                       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 472, codigoAfip: '551001', nombre: 'Otros Conceptos no Rem. c/Ret ART',                       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 473, codigoAfip: '551001', nombre: 'Otros Conceptos no Rem. c/Ret ART',                       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 474, codigoAfip: '551001', nombre: 'Otros Conceptos no Rem. c/Ret ART',                       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 475, codigoAfip: '551001', nombre: 'Otros Conceptos no Rem. c/Ret ART',                       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 476, codigoAfip: '551001', nombre: 'Otros Conceptos no Rem. c/Ret ART',                       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 477, codigoAfip: '551001', nombre: 'Otros Conceptos no Rem. c/Ret ART',                       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 478, codigoAfip: '551001', nombre: 'Otros Conceptos no Rem. c/Ret ART',                       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 479, codigoAfip: '551001', nombre: 'Otros Conceptos no Rem. c/Ret ART',                       tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 480, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 481, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 482, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 483, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 484, codigoAfip: '551000', nombre: 'Otros Conceptos no Rem. sin Retenciones',                 tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 491, codigoAfip: '560001', nombre: 'Asign. din. - Dec. 390/2021',                             tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 492, codigoAfip: '560002', nombre: 'Asign. din. - Dec. 390/2021',                             tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 493, codigoAfip: '560003', nombre: 'Asign. din. - Dec. 390/2021',                             tieneMemo: true,  tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 494, codigoAfip: '560001', nombre: 'Asign. din. - Dec. 390/2021',                             tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 495, codigoAfip: '560002', nombre: 'Asign. din. - Dec. 390/2021',                             tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 496, codigoAfip: '560003', nombre: 'Asign. din. - Dec. 390/2021',                             tieneMemo: true,  tieneCantidad: true,  tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 501, codigoAfip: '810004', nombre: 'Acuerdo Sindicato',                                       tieneMemo: false, tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub411_469',  divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 502, codigoAfip: '810002', nombre: 'Acuerdos Obra Social',                                    tieneMemo: false, tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub411_469',  divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 503, codigoAfip: '821001', nombre: 'Acuerdos Federaciones y Otros',                           tieneMemo: false, tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub411_469',  divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 504, codigoAfip: '810006', nombre: 'RENATEA s/ no Rem',                                       tieneMemo: false, tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub411_469',  divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 511, codigoAfip: '821000', nombre: 'Otros conceptos de retenciones s/cptos.no remuner.',      tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub411_469',  divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 512, codigoAfip: '821000', nombre: 'Otros conceptos de retenciones s/cptos.no remuner.',      tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub411_469',  divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 513, codigoAfip: '821000', nombre: 'Otros conceptos de retenciones s/cptos.no remuner.',      tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub411_469',  divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 514, codigoAfip: '821000', nombre: 'Otros conceptos de retenciones s/cptos.no remuner.',      tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub411_469',  divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 515, codigoAfip: '821000', nombre: 'Otros conceptos de retenciones s/cptos.no remuner.',      tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub411_469',  divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 516, codigoAfip: '821000', nombre: 'Otros conceptos de retenciones s/cptos.no remuner.',      tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub411_469',  divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 517, codigoAfip: '821000', nombre: 'Otros conceptos de retenciones s/cptos.no remuner.',      tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub411_469',  divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 520, codigoAfip: '821000', nombre: 'Ajuste SIPA Dec 792/2020',                                tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub411_469',  divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 551, codigoAfip: '810000', nombre: 'Jubilacion s/Rem',                                        tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: true,  tieneImpMax: true,  baseColumna: 'sub1_199_plus_411_469', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 552, codigoAfip: '810001', nombre: 'Ley 19032 s/Rem',                                         tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: true,  tieneImpMax: true,  baseColumna: 'sub1_199_plus_411_469', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 553, codigoAfip: '810002', nombre: 'Obra Social s/Rem',                                       tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199_plus_411_469', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 554, codigoAfip: '810009', nombre: 'Obra Social Adherente s/Rem',                             tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199_plus_411_469', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 555, codigoAfip: '810003', nombre: 'Anssal s/Rem',                                            tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199_plus_411_469', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 556, codigoAfip: '810004', nombre: 'Sindicato s/Rem',                                         tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199_plus_411_469', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 557, codigoAfip: '821000', nombre: 'Federaciones y Otros s/Rem',                              tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199_plus_411_469', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 558, codigoAfip: '821000', nombre: 'Otros conceptos de retenciones s/cptos.no remuner.',      tieneMemo: true,  tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199_plus_411_469', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 559, codigoAfip: '810006', nombre: 'RENATEA s/Rem',                                           tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: true,  tieneImpMax: true,  baseColumna: 'sub1_199_plus_411_469', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 560, codigoAfip: '821000', nombre: 'Otros conceptos de retenciones s/Rem',                    tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199_plus_411_469', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 561, codigoAfip: '821000', nombre: 'Otros conceptos de retenciones s/Rem',                    tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199_plus_411_469', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 562, codigoAfip: '821000', nombre: 'Otros conceptos de retenciones s/Rem',                    tieneMemo: true,  tieneCantidad: false, tienePct: true,  tieneImpConceptoNro: false, tieneImporte: false, tieneImpMin: false, tieneImpMax: false, baseColumna: 'sub1_199_plus_411_469', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 601, codigoAfip: '560005A', nombre: 'Asign. no remunerativa Dec 841/2022',                    tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 602, codigoAfip: '560005B', nombre: 'Asign. no remunerativa Dec 841/2022 (con ART)',          tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 603, codigoAfip: '560004', nombre: 'Asign. din. - Dec. 551/2022 (con ART)',                   tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 604, codigoAfip: '560006A', nombre: 'Asignacion no Remunerativa Dcto 438/2023',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 605, codigoAfip: '560006B', nombre: 'Asignacion no Remunerativa Dcto 438/2023 (con ART)',     tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: true,  tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 610, codigoAfip: '520000', nombre: 'Beneficios Sociales',                                     tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 611, codigoAfip: '520001', nombre: 'Servicio de Comedor',                                     tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 612, codigoAfip: '520002', nombre: 'Gastos Medicos',                                          tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 613, codigoAfip: '520003', nombre: 'Provision de ropa de trabajo',                            tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 614, codigoAfip: '520004', nombre: 'Guarderia',                                               tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 615, codigoAfip: '520005', nombre: 'Provision de utiles escolares',                           tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 616, codigoAfip: '520006', nombre: 'Gastos de sepelio',                                       tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 617, codigoAfip: '520007', nombre: 'Cursos de capacitacion',                                  tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 618, codigoAfip: '520008', nombre: 'Becas',                                                   tieneMemo: false, tieneCantidad: false, tienePct: false, tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
  { numeroSos: 620, codigoAfip: '510002', nombre: 'ASIGNACION POR HIJO/HIJO CON DISCAPACIDAD',               tieneMemo: true,  tieneCantidad: true,  tienePct: true,  tieneImpConceptoNro: false, tieneImporte: true,  tieneImpMin: false, tieneImpMax: false, baseColumna: 'importe_fijo', divHsNorm: 1,   divCantidad: 1  },
];

async function main() {
  if (!process.env.DATABASE_URL) throw new Error('Falta DATABASE_URL');

  console.log(`[${DRY_RUN ? 'dry-run' : 'seed'}] Procesando ${CONCEPTOS.length} conceptos SOS...`);

  let inserted = 0;
  let updated = 0;

  for (const c of CONCEPTOS) {
    if (DRY_RUN) {
      inserted++;
      continue;
    }

    const [existing] = await db
      .select({ id: payrollConceptosSosCatalog.id })
      .from(payrollConceptosSosCatalog)
      .where(eq(payrollConceptosSosCatalog.numeroSos, c.numeroSos))
      .limit(1);

    if (existing) {
      await db
        .update(payrollConceptosSosCatalog)
        .set({ ...c, updatedAt: new Date() })
        .where(eq(payrollConceptosSosCatalog.id, existing.id));
      updated++;
    } else {
      await db.insert(payrollConceptosSosCatalog).values(c);
      inserted++;
    }
  }

  console.log(`[${DRY_RUN ? 'dry-run' : 'ok'}] Insertados: ${inserted} | Actualizados: ${updated}`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
