-- Fase 1 (higiene) del plan de rediseño de BD — generado por src/scripts/gen-fase1-sql.ts
-- Generado: 2026-07-30 contra la BD real.
-- APLICAR SOLO EN NEW_DB, POST-CUTOVER. NUNCA en ORIGINAL_DB. NUNCA db:push.
-- CREATE INDEX CONCURRENTLY no puede correr dentro de una transacción:
-- aplicar sentencia por sentencia (script bun con postgres, simple: true).

-- ============ A) 115 índices de FK faltantes ============

create index concurrently if not exists idx_account_user_id on "account" ("user_id");
create index concurrently if not exists idx_account_override_account_id on "account_override" ("account_id");
create index concurrently if not exists idx_accounting_account_parent_id on "accounting_account" ("parent_id");
create index concurrently if not exists idx_accounting_log_fiscal_year_id on "accounting_log" ("fiscal_year_id");
create index concurrently if not exists idx_accounting_log_user_id on "accounting_log" ("user_id");
create index concurrently if not exists idx_accounting_period_closed_by on "accounting_period" ("closed_by");
create index concurrently if not exists idx_afip_empleadores_convenio_convenio_id on "afip_empleadores_convenio" ("convenio_id");
create index concurrently if not exists idx_agent_conversation_organization_id on "agent_conversation" ("organization_id");
create index concurrently if not exists idx_agent_conversation_user_id on "agent_conversation" ("user_id");
create index concurrently if not exists idx_agent_message_conversation_id on "agent_message" ("conversation_id");
create index concurrently if not exists idx_agent_run_client_id on "agent_run" ("client_id");
create index concurrently if not exists idx_agent_run_conversation_id on "agent_run" ("conversation_id");
create index concurrently if not exists idx_agent_run_organization_id on "agent_run" ("organization_id");
create index concurrently if not exists idx_agent_run_representative_id on "agent_run" ("representative_id");
create index concurrently if not exists idx_agent_run_user_id on "agent_run" ("user_id");
create index concurrently if not exists idx_alert_assigned_to_user_id on "alert" ("assigned_to_user_id");
create index concurrently if not exists idx_alert_client_id on "alert" ("client_id");
create index concurrently if not exists idx_alert_representative_id on "alert" ("representative_id");
create index concurrently if not exists idx_alert_resolved_by_user_id on "alert" ("resolved_by_user_id");
create index concurrently if not exists idx_bank_account_client_id on "bank_account" ("client_id");
create index concurrently if not exists idx_bank_account_representative_id on "bank_account" ("representative_id");
create index concurrently if not exists idx_bank_invoice_match_bank_transaction_id on "bank_invoice_match" ("bank_transaction_id");
create index concurrently if not exists idx_bank_invoice_match_invoice_id on "bank_invoice_match" ("invoice_id");
create index concurrently if not exists idx_bank_invoice_match_reviewed_by_user_id on "bank_invoice_match" ("reviewed_by_user_id");
create index concurrently if not exists idx_bank_transaction_bank_account_id on "bank_transaction" ("bank_account_id");
create index concurrently if not exists idx_client_actividad_default_id on "client" ("actividad_default_id");
create index concurrently if not exists idx_client_condicion_default_id on "client" ("condicion_default_id");
create index concurrently if not exists idx_client_contratacion_default_id on "client" ("contratacion_default_id");
create index concurrently if not exists idx_client_obra_social_default_id on "client" ("obra_social_default_id");
create index concurrently if not exists idx_client_payroll_plantilla_empleado_id on "client" ("payroll_plantilla_empleado_id");
create index concurrently if not exists idx_client_representative_id on "client" ("representative_id");
create index concurrently if not exists idx_client_siniestrado_default_id on "client" ("siniestrado_default_id");
create index concurrently if not exists idx_client_situacion_default_id on "client" ("situacion_default_id");
create index concurrently if not exists idx_client_tipo_empresa_id on "client" ("tipo_empresa_id");
create index concurrently if not exists idx_client_zona_default_id on "client" ("zona_default_id");
create index concurrently if not exists idx_cmv_annex_organization_id on "cmv_annex" ("organization_id");
create index concurrently if not exists idx_concepto_sos_concepto_afip_id on "concepto_sos" ("concepto_afip_id");
create index concurrently if not exists idx_concepto_sos_client_client_id on "concepto_sos_client" ("client_id");
create index concurrently if not exists idx_data_source_event_client_id on "data_source_event" ("client_id");
create index concurrently if not exists idx_data_source_event_organization_id on "data_source_event" ("organization_id");
create index concurrently if not exists idx_data_source_event_representative_id on "data_source_event" ("representative_id");
create index concurrently if not exists idx_data_source_event_source_job_id on "data_source_event" ("source_job_id");
create index concurrently if not exists idx_debt_client_id on "debt" ("client_id");
create index concurrently if not exists idx_document_representative_id on "document" ("representative_id");
create index concurrently if not exists idx_due_date_client_id on "due_date" ("client_id");
create index concurrently if not exists idx_due_date_completed_by_user_id on "due_date" ("completed_by_user_id");
create index concurrently if not exists idx_employee_event_created_by_user_id on "employee_event" ("created_by_user_id");
create index concurrently if not exists idx_employee_event_empleado_id on "employee_event" ("empleado_id");
create index concurrently if not exists idx_financial_movement_classification_client_id on "financial_movement_classification" ("client_id");
create index concurrently if not exists idx_financial_movement_classification_representative_id on "financial_movement_classification" ("representative_id");
create index concurrently if not exists idx_financial_statement_approved_by on "financial_statement" ("approved_by");
create index concurrently if not exists idx_financial_statement_organization_id on "financial_statement" ("organization_id");
create index concurrently if not exists idx_financial_statement_pdf_generated_by on "financial_statement" ("pdf_generated_by");
create index concurrently if not exists idx_fiscal_year_closed_by on "fiscal_year" ("closed_by");
create index concurrently if not exists idx_fiscal_year_reopened_by on "fiscal_year" ("reopened_by");
create index concurrently if not exists idx_fixed_asset_accum_depr_account_id on "fixed_asset" ("accum_depr_account_id");
create index concurrently if not exists idx_fixed_asset_asset_account_id on "fixed_asset" ("asset_account_id");
create index concurrently if not exists idx_fixed_asset_created_by on "fixed_asset" ("created_by");
create index concurrently if not exists idx_fixed_asset_depr_expense_account_id on "fixed_asset" ("depr_expense_account_id");
create index concurrently if not exists idx_iibb_liquidacion_profile_id on "iibb_liquidacion" ("profile_id");
create index concurrently if not exists idx_iibb_liquidacion_representative_id on "iibb_liquidacion" ("representative_id");
create index concurrently if not exists idx_invitation_inviter_id on "invitation" ("inviter_id");
create index concurrently if not exists idx_invitation_organization_id on "invitation" ("organization_id");
create index concurrently if not exists idx_invoice_client_id on "invoice" ("client_id");
create index concurrently if not exists idx_invoice_attachment_document_id on "invoice_attachment" ("document_id");
create index concurrently if not exists idx_invoice_attachment_notification_id on "invoice_attachment" ("notification_id");
create index concurrently if not exists idx_job_representative_id on "job" ("representative_id");
create index concurrently if not exists idx_job_log_job_id on "job_log" ("job_id");
create index concurrently if not exists idx_journal_entry_created_by on "journal_entry" ("created_by");
create index concurrently if not exists idx_journal_entry_fiscal_year_id on "journal_entry" ("fiscal_year_id");
create index concurrently if not exists idx_journal_entry_mapping_rule_id on "journal_entry" ("mapping_rule_id");
create index concurrently if not exists idx_journal_entry_period_id on "journal_entry" ("period_id");
create index concurrently if not exists idx_journal_entry_voided_by on "journal_entry" ("voided_by");
create index concurrently if not exists idx_journal_entry_line_account_id on "journal_entry_line" ("account_id");
create index concurrently if not exists idx_journal_entry_line_period_id on "journal_entry_line" ("period_id");
create index concurrently if not exists idx_ledger_mapping_rule_line_account_id on "ledger_mapping_rule_line" ("account_id");
create index concurrently if not exists idx_liquidacion_import_concepto_valor_concepto_id on "liquidacion_import_concepto_valor" ("concepto_id");
create index concurrently if not exists idx_liquidacion_import_empleado_actividad_id on "liquidacion_import_empleado" ("actividad_id");
create index concurrently if not exists idx_liquidacion_import_empleado_categoria_id on "liquidacion_import_empleado" ("categoria_id");
create index concurrently if not exists idx_liquidacion_import_empleado_condicion_id on "liquidacion_import_empleado" ("condicion_id");
create index concurrently if not exists idx_liquidacion_import_empleado_convenio_id on "liquidacion_import_empleado" ("convenio_id");
create index concurrently if not exists idx_liquidacion_import_empleado_localidad_id on "liquidacion_import_empleado" ("localidad_id");
create index concurrently if not exists idx_liquidacion_import_empleado_modalidad_contratacion_id on "liquidacion_import_empleado" ("modalidad_contratacion_id");
create index concurrently if not exists idx_liquidacion_import_empleado_nacionalidad_id on "liquidacion_import_empleado" ("nacionalidad_id");
create index concurrently if not exists idx_liquidacion_import_empleado_obra_social_id on "liquidacion_import_empleado" ("obra_social_id");
create index concurrently if not exists idx_liquidacion_import_empleado_provincia_id on "liquidacion_import_empleado" ("provincia_id");
create index concurrently if not exists idx_liquidacion_import_empleado_siniestrado_id on "liquidacion_import_empleado" ("siniestrado_id");
create index concurrently if not exists idx_liquidacion_import_empleado_situacion_id on "liquidacion_import_empleado" ("situacion_id");
create index concurrently if not exists idx_liquidacion_import_empleado_zona_id on "liquidacion_import_empleado" ("zona_id");
create index concurrently if not exists idx_liquidacion_import_recibo_obra_social_id on "liquidacion_import_recibo" ("obra_social_id");
create index concurrently if not exists idx_liquidacion_import_recibo_situacion_revista1_id on "liquidacion_import_recibo" ("situacion_revista1_id");
create index concurrently if not exists idx_liquidacion_import_recibo_situacion_revista2_id on "liquidacion_import_recibo" ("situacion_revista2_id");
create index concurrently if not exists idx_liquidacion_import_recibo_situacion_revista3_id on "liquidacion_import_recibo" ("situacion_revista3_id");
create index concurrently if not exists idx_lsd_perfil_concepto_concepto_afip_id on "lsd_perfil_concepto" ("concepto_afip_id");
create index concurrently if not exists idx_member_organization_id on "member" ("organization_id");
create index concurrently if not exists idx_member_user_id on "member" ("user_id");
create index concurrently if not exists idx_movements_user_id on "movements" ("user_id");
create index concurrently if not exists idx_notification_assigned_to_user_id on "notification" ("assigned_to_user_id");
create index concurrently if not exists idx_notification_client_id on "notification" ("client_id");
create index concurrently if not exists idx_notification_resolved_by_user_id on "notification" ("resolved_by_user_id");
create index concurrently if not exists idx_payroll_concepto_representative_id on "payroll_concepto" ("representative_id");
create index concurrently if not exists idx_payroll_convenio_client_id on "payroll_convenio" ("client_id");
create index concurrently if not exists idx_payroll_convenio_representative_id on "payroll_convenio" ("representative_id");
create index concurrently if not exists idx_payroll_convenio_categoria_convenio_id on "payroll_convenio_categoria" ("convenio_id");
create index concurrently if not exists idx_payroll_escala_categoria_id on "payroll_escala" ("categoria_id");
create index concurrently if not exists idx_payroll_period_novelty_applied_to_recibo_id on "payroll_period_novelty" ("applied_to_recibo_id");
create index concurrently if not exists idx_payroll_period_novelty_empleado_id on "payroll_period_novelty" ("empleado_id");
create index concurrently if not exists idx_payroll_receipt_template_client_id on "payroll_receipt_template" ("client_id");
create index concurrently if not exists idx_representative_user_id on "representative" ("user_id");
create index concurrently if not exists idx_representative_request_client_id on "representative_request" ("client_id");
create index concurrently if not exists idx_representative_request_organization_id on "representative_request" ("organization_id");
create index concurrently if not exists idx_representative_request_representative_id on "representative_request" ("representative_id");
create index concurrently if not exists idx_representative_request_requested_by_user_id on "representative_request" ("requested_by_user_id");
create index concurrently if not exists idx_representative_user_access_user_id on "representative_user_access" ("user_id");
create index concurrently if not exists idx_session_user_id on "session" ("user_id");

-- ============ B) updated_at faltante en 36 tablas ============

alter table "accounting_log" add column if not exists updated_at timestamptz not null default now();
alter table "accounting_period" add column if not exists updated_at timestamptz not null default now();
alter table "agent_message" add column if not exists updated_at timestamptz not null default now();
alter table "agent_run" add column if not exists updated_at timestamptz not null default now();
alter table "bank_account" add column if not exists updated_at timestamptz not null default now();
alter table "bank_invoice_match" add column if not exists updated_at timestamptz not null default now();
alter table "bank_transaction" add column if not exists updated_at timestamptz not null default now();
alter table "client_risk_snapshot" add column if not exists updated_at timestamptz not null default now();
alter table "concepto_sos_client" add column if not exists updated_at timestamptz not null default now();
alter table "data_source_event" add column if not exists updated_at timestamptz not null default now();
alter table "employee_event" add column if not exists updated_at timestamptz not null default now();
alter table "financial_movement_classification" add column if not exists updated_at timestamptz not null default now();
alter table "fiscal_year" add column if not exists updated_at timestamptz not null default now();
alter table "invitation" add column if not exists updated_at timestamptz not null default now();
alter table "job_log" add column if not exists updated_at timestamptz not null default now();
alter table "journal_entry_line" add column if not exists updated_at timestamptz not null default now();
alter table "ledger_mapping_rule_line" add column if not exists updated_at timestamptz not null default now();
alter table "member" add column if not exists updated_at timestamptz not null default now();
alter table "obra_social" add column if not exists updated_at timestamptz not null default now();
alter table "organization_module" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_actividad" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_condicion" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_localidad" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_lsd_presentacion" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_modalidad_contratacion" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_nacionalidad" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_period_novelty" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_provincia" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_receipt_template" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_siniestrado" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_situacion" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_tipo_empresa" add column if not exists updated_at timestamptz not null default now();
alter table "payroll_zona" add column if not exists updated_at timestamptz not null default now();
alter table "representative_request" add column if not exists updated_at timestamptz not null default now();
alter table "representative_user_access" add column if not exists updated_at timestamptz not null default now();
alter table "tax_projection" add column if not exists updated_at timestamptz not null default now();

-- ============ C) created_at faltante en 3 tablas ============

alter table "agent_run" add column if not exists created_at timestamptz not null default now();
alter table "payroll_lsd_presentacion" add column if not exists created_at timestamptz not null default now();
alter table "tax_projection" add column if not exists created_at timestamptz not null default now();
