/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoOrganizationRouteImport } from './routes/no-organization'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientRouteRouteImport } from './routes/_client/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as ApiCopilotkitRouteImport } from './routes/api/copilotkit'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ClientPortalIndexRouteImport } from './routes/_client/portal/index'
import { Route as AuthedVencimientosIndexRouteImport } from './routes/_authed/vencimientos/index'
import { Route as AuthedSueldosIndexRouteImport } from './routes/_authed/sueldos/index'
import { Route as AuthedScan_pdfIndexRouteImport } from './routes/_authed/scan_pdf/index'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed/products/index'
import { Route as AuthedNotificationsIndexRouteImport } from './routes/_authed/notifications/index'
import { Route as AuthedJobsIndexRouteImport } from './routes/_authed/jobs/index'
import { Route as AuthedIvaIndexRouteImport } from './routes/_authed/iva/index'
import { Route as AuthedInvoicesIndexRouteImport } from './routes/_authed/invoices/index'
import { Route as AuthedIibbIndexRouteImport } from './routes/_authed/iibb/index'
import { Route as AuthedClientsIndexRouteImport } from './routes/_authed/clients/index'
import { Route as AuthedChatIndexRouteImport } from './routes/_authed/chat/index'
import { Route as AuthedBankIndexRouteImport } from './routes/_authed/bank/index'
import { Route as AuthedAnalyticsIndexRouteImport } from './routes/_authed/analytics/index'
import { Route as AuthedAlertsIndexRouteImport } from './routes/_authed/alerts/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAccountingIndexRouteImport } from './routes/_authed/accounting/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedProductsIdRouteImport } from './routes/_authed/products/$id'
import { Route as AuthedChatIdRouteImport } from './routes/_authed/chat/$id'
import { Route as ClientPortalSolicitudesIndexRouteImport } from './routes/_client/portal/solicitudes/index'
import { Route as AuthedSueldosProfileIdIndexRouteImport } from './routes/_authed/sueldos/$profileId/index'
import { Route as AuthedClientsClientIdIndexRouteImport } from './routes/_authed/clients/$clientId/index'
import { Route as AuthedClientsClientIdProfileIdIndexRouteImport } from './routes/_authed/clients/$clientId/$profileId/index'

const NoOrganizationRoute = NoOrganizationRouteImport.update({
  id: '/no-organization',
  path: '/no-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRouteRoute = ClientRouteRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotkitRoute = ApiCopilotkitRouteImport.update({
  id: '/api/copilotkit',
  path: '/api/copilotkit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalIndexRoute = ClientPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const AuthedVencimientosIndexRoute = AuthedVencimientosIndexRouteImport.update({
  id: '/vencimientos/',
  path: '/vencimientos/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSueldosIndexRoute = AuthedSueldosIndexRouteImport.update({
  id: '/sueldos/',
  path: '/sueldos/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedScan_pdfIndexRoute = AuthedScan_pdfIndexRouteImport.update({
  id: '/scan_pdf/',
  path: '/scan_pdf/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedNotificationsIndexRoute =
  AuthedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedJobsIndexRoute = AuthedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedIvaIndexRoute = AuthedIvaIndexRouteImport.update({
  id: '/iva/',
  path: '/iva/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedInvoicesIndexRoute = AuthedInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedIibbIndexRoute = AuthedIibbIndexRouteImport.update({
  id: '/iibb/',
  path: '/iibb/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedClientsIndexRoute = AuthedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedChatIndexRoute = AuthedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedBankIndexRoute = AuthedBankIndexRouteImport.update({
  id: '/bank/',
  path: '/bank/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAnalyticsIndexRoute = AuthedAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAlertsIndexRoute = AuthedAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAccountingIndexRoute = AuthedAccountingIndexRouteImport.update({
  id: '/accounting/',
  path: '/accounting/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProductsIdRoute = AuthedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedChatIdRoute = AuthedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ClientPortalSolicitudesIndexRoute =
  ClientPortalSolicitudesIndexRouteImport.update({
    id: '/portal/solicitudes/',
    path: '/portal/solicitudes/',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const AuthedSueldosProfileIdIndexRoute =
  AuthedSueldosProfileIdIndexRouteImport.update({
    id: '/sueldos/$profileId/',
    path: '/sueldos/$profileId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedClientsClientIdIndexRoute =
  AuthedClientsClientIdIndexRouteImport.update({
    id: '/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedClientsClientIdProfileIdIndexRoute =
  AuthedClientsClientIdProfileIdIndexRouteImport.update({
    id: '/clients/$clientId/$profileId/',
    path: '/clients/$clientId/$profileId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/no-organization': typeof NoOrganizationRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/copilotkit': typeof ApiCopilotkitRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/chat/$id': typeof AuthedChatIdRoute
  '/products/$id': typeof AuthedProductsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/accounting/': typeof AuthedAccountingIndexRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/alerts/': typeof AuthedAlertsIndexRoute
  '/analytics/': typeof AuthedAnalyticsIndexRoute
  '/bank/': typeof AuthedBankIndexRoute
  '/chat/': typeof AuthedChatIndexRoute
  '/clients/': typeof AuthedClientsIndexRoute
  '/iibb/': typeof AuthedIibbIndexRoute
  '/invoices/': typeof AuthedInvoicesIndexRoute
  '/iva/': typeof AuthedIvaIndexRoute
  '/jobs/': typeof AuthedJobsIndexRoute
  '/notifications/': typeof AuthedNotificationsIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/scan_pdf/': typeof AuthedScan_pdfIndexRoute
  '/sueldos/': typeof AuthedSueldosIndexRoute
  '/vencimientos/': typeof AuthedVencimientosIndexRoute
  '/portal/': typeof ClientPortalIndexRoute
  '/clients/$clientId/': typeof AuthedClientsClientIdIndexRoute
  '/sueldos/$profileId/': typeof AuthedSueldosProfileIdIndexRoute
  '/portal/solicitudes/': typeof ClientPortalSolicitudesIndexRoute
  '/clients/$clientId/$profileId/': typeof AuthedClientsClientIdProfileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/no-organization': typeof NoOrganizationRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/copilotkit': typeof ApiCopilotkitRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/chat/$id': typeof AuthedChatIdRoute
  '/products/$id': typeof AuthedProductsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/accounting': typeof AuthedAccountingIndexRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/alerts': typeof AuthedAlertsIndexRoute
  '/analytics': typeof AuthedAnalyticsIndexRoute
  '/bank': typeof AuthedBankIndexRoute
  '/chat': typeof AuthedChatIndexRoute
  '/clients': typeof AuthedClientsIndexRoute
  '/iibb': typeof AuthedIibbIndexRoute
  '/invoices': typeof AuthedInvoicesIndexRoute
  '/iva': typeof AuthedIvaIndexRoute
  '/jobs': typeof AuthedJobsIndexRoute
  '/notifications': typeof AuthedNotificationsIndexRoute
  '/products': typeof AuthedProductsIndexRoute
  '/scan_pdf': typeof AuthedScan_pdfIndexRoute
  '/sueldos': typeof AuthedSueldosIndexRoute
  '/vencimientos': typeof AuthedVencimientosIndexRoute
  '/portal': typeof ClientPortalIndexRoute
  '/clients/$clientId': typeof AuthedClientsClientIdIndexRoute
  '/sueldos/$profileId': typeof AuthedSueldosProfileIdIndexRoute
  '/portal/solicitudes': typeof ClientPortalSolicitudesIndexRoute
  '/clients/$clientId/$profileId': typeof AuthedClientsClientIdProfileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_client': typeof ClientRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/no-organization': typeof NoOrganizationRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/copilotkit': typeof ApiCopilotkitRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/chat/$id': typeof AuthedChatIdRoute
  '/_authed/products/$id': typeof AuthedProductsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/accounting/': typeof AuthedAccountingIndexRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/alerts/': typeof AuthedAlertsIndexRoute
  '/_authed/analytics/': typeof AuthedAnalyticsIndexRoute
  '/_authed/bank/': typeof AuthedBankIndexRoute
  '/_authed/chat/': typeof AuthedChatIndexRoute
  '/_authed/clients/': typeof AuthedClientsIndexRoute
  '/_authed/iibb/': typeof AuthedIibbIndexRoute
  '/_authed/invoices/': typeof AuthedInvoicesIndexRoute
  '/_authed/iva/': typeof AuthedIvaIndexRoute
  '/_authed/jobs/': typeof AuthedJobsIndexRoute
  '/_authed/notifications/': typeof AuthedNotificationsIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/scan_pdf/': typeof AuthedScan_pdfIndexRoute
  '/_authed/sueldos/': typeof AuthedSueldosIndexRoute
  '/_authed/vencimientos/': typeof AuthedVencimientosIndexRoute
  '/_client/portal/': typeof ClientPortalIndexRoute
  '/_authed/clients/$clientId/': typeof AuthedClientsClientIdIndexRoute
  '/_authed/sueldos/$profileId/': typeof AuthedSueldosProfileIdIndexRoute
  '/_client/portal/solicitudes/': typeof ClientPortalSolicitudesIndexRoute
  '/_authed/clients/$clientId/$profileId/': typeof AuthedClientsClientIdProfileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/no-organization'
    | '/api/agent'
    | '/api/copilotkit'
    | '/invite/$invitationId'
    | '/chat/$id'
    | '/products/$id'
    | '/api/auth/$'
    | '/accounting/'
    | '/admin/'
    | '/alerts/'
    | '/analytics/'
    | '/bank/'
    | '/chat/'
    | '/clients/'
    | '/iibb/'
    | '/invoices/'
    | '/iva/'
    | '/jobs/'
    | '/notifications/'
    | '/products/'
    | '/scan_pdf/'
    | '/sueldos/'
    | '/vencimientos/'
    | '/portal/'
    | '/clients/$clientId/'
    | '/sueldos/$profileId/'
    | '/portal/solicitudes/'
    | '/clients/$clientId/$profileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/no-organization'
    | '/api/agent'
    | '/api/copilotkit'
    | '/invite/$invitationId'
    | '/chat/$id'
    | '/products/$id'
    | '/api/auth/$'
    | '/accounting'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/bank'
    | '/chat'
    | '/clients'
    | '/iibb'
    | '/invoices'
    | '/iva'
    | '/jobs'
    | '/notifications'
    | '/products'
    | '/scan_pdf'
    | '/sueldos'
    | '/vencimientos'
    | '/portal'
    | '/clients/$clientId'
    | '/sueldos/$profileId'
    | '/portal/solicitudes'
    | '/clients/$clientId/$profileId'
  id:
    | '__root__'
    | '/_authed'
    | '/_client'
    | '/login'
    | '/no-organization'
    | '/api/agent'
    | '/api/copilotkit'
    | '/invite/$invitationId'
    | '/_authed/'
    | '/_authed/chat/$id'
    | '/_authed/products/$id'
    | '/api/auth/$'
    | '/_authed/accounting/'
    | '/_authed/admin/'
    | '/_authed/alerts/'
    | '/_authed/analytics/'
    | '/_authed/bank/'
    | '/_authed/chat/'
    | '/_authed/clients/'
    | '/_authed/iibb/'
    | '/_authed/invoices/'
    | '/_authed/iva/'
    | '/_authed/jobs/'
    | '/_authed/notifications/'
    | '/_authed/products/'
    | '/_authed/scan_pdf/'
    | '/_authed/sueldos/'
    | '/_authed/vencimientos/'
    | '/_client/portal/'
    | '/_authed/clients/$clientId/'
    | '/_authed/sueldos/$profileId/'
    | '/_client/portal/solicitudes/'
    | '/_authed/clients/$clientId/$profileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  ClientRouteRoute: typeof ClientRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  NoOrganizationRoute: typeof NoOrganizationRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiCopilotkitRoute: typeof ApiCopilotkitRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/no-organization': {
      id: '/no-organization'
      path: '/no-organization'
      fullPath: '/no-organization'
      preLoaderRoute: typeof NoOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilotkit': {
      id: '/api/copilotkit'
      path: '/api/copilotkit'
      fullPath: '/api/copilotkit'
      preLoaderRoute: typeof ApiCopilotkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/portal/': {
      id: '/_client/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof ClientPortalIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_authed/vencimientos/': {
      id: '/_authed/vencimientos/'
      path: '/vencimientos'
      fullPath: '/vencimientos/'
      preLoaderRoute: typeof AuthedVencimientosIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sueldos/': {
      id: '/_authed/sueldos/'
      path: '/sueldos'
      fullPath: '/sueldos/'
      preLoaderRoute: typeof AuthedSueldosIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/scan_pdf/': {
      id: '/_authed/scan_pdf/'
      path: '/scan_pdf'
      fullPath: '/scan_pdf/'
      preLoaderRoute: typeof AuthedScan_pdfIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/notifications/': {
      id: '/_authed/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthedNotificationsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/jobs/': {
      id: '/_authed/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthedJobsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/iva/': {
      id: '/_authed/iva/'
      path: '/iva'
      fullPath: '/iva/'
      preLoaderRoute: typeof AuthedIvaIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/invoices/': {
      id: '/_authed/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthedInvoicesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/iibb/': {
      id: '/_authed/iibb/'
      path: '/iibb'
      fullPath: '/iibb/'
      preLoaderRoute: typeof AuthedIibbIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/clients/': {
      id: '/_authed/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthedClientsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/chat/': {
      id: '/_authed/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthedChatIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/bank/': {
      id: '/_authed/bank/'
      path: '/bank'
      fullPath: '/bank/'
      preLoaderRoute: typeof AuthedBankIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/analytics/': {
      id: '/_authed/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthedAnalyticsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/alerts/': {
      id: '/_authed/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AuthedAlertsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/accounting/': {
      id: '/_authed/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AuthedAccountingIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/products/$id': {
      id: '/_authed/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthedProductsIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/chat/$id': {
      id: '/_authed/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthedChatIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_client/portal/solicitudes/': {
      id: '/_client/portal/solicitudes/'
      path: '/portal/solicitudes'
      fullPath: '/portal/solicitudes/'
      preLoaderRoute: typeof ClientPortalSolicitudesIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_authed/sueldos/$profileId/': {
      id: '/_authed/sueldos/$profileId/'
      path: '/sueldos/$profileId'
      fullPath: '/sueldos/$profileId/'
      preLoaderRoute: typeof AuthedSueldosProfileIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/clients/$clientId/': {
      id: '/_authed/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AuthedClientsClientIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/clients/$clientId/$profileId/': {
      id: '/_authed/clients/$clientId/$profileId/'
      path: '/clients/$clientId/$profileId'
      fullPath: '/clients/$clientId/$profileId/'
      preLoaderRoute: typeof AuthedClientsClientIdProfileIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedChatIdRoute: typeof AuthedChatIdRoute
  AuthedProductsIdRoute: typeof AuthedProductsIdRoute
  AuthedAccountingIndexRoute: typeof AuthedAccountingIndexRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAlertsIndexRoute: typeof AuthedAlertsIndexRoute
  AuthedAnalyticsIndexRoute: typeof AuthedAnalyticsIndexRoute
  AuthedBankIndexRoute: typeof AuthedBankIndexRoute
  AuthedChatIndexRoute: typeof AuthedChatIndexRoute
  AuthedClientsIndexRoute: typeof AuthedClientsIndexRoute
  AuthedIibbIndexRoute: typeof AuthedIibbIndexRoute
  AuthedInvoicesIndexRoute: typeof AuthedInvoicesIndexRoute
  AuthedIvaIndexRoute: typeof AuthedIvaIndexRoute
  AuthedJobsIndexRoute: typeof AuthedJobsIndexRoute
  AuthedNotificationsIndexRoute: typeof AuthedNotificationsIndexRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedScan_pdfIndexRoute: typeof AuthedScan_pdfIndexRoute
  AuthedSueldosIndexRoute: typeof AuthedSueldosIndexRoute
  AuthedVencimientosIndexRoute: typeof AuthedVencimientosIndexRoute
  AuthedClientsClientIdIndexRoute: typeof AuthedClientsClientIdIndexRoute
  AuthedSueldosProfileIdIndexRoute: typeof AuthedSueldosProfileIdIndexRoute
  AuthedClientsClientIdProfileIdIndexRoute: typeof AuthedClientsClientIdProfileIdIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedChatIdRoute: AuthedChatIdRoute,
  AuthedProductsIdRoute: AuthedProductsIdRoute,
  AuthedAccountingIndexRoute: AuthedAccountingIndexRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAlertsIndexRoute: AuthedAlertsIndexRoute,
  AuthedAnalyticsIndexRoute: AuthedAnalyticsIndexRoute,
  AuthedBankIndexRoute: AuthedBankIndexRoute,
  AuthedChatIndexRoute: AuthedChatIndexRoute,
  AuthedClientsIndexRoute: AuthedClientsIndexRoute,
  AuthedIibbIndexRoute: AuthedIibbIndexRoute,
  AuthedInvoicesIndexRoute: AuthedInvoicesIndexRoute,
  AuthedIvaIndexRoute: AuthedIvaIndexRoute,
  AuthedJobsIndexRoute: AuthedJobsIndexRoute,
  AuthedNotificationsIndexRoute: AuthedNotificationsIndexRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedScan_pdfIndexRoute: AuthedScan_pdfIndexRoute,
  AuthedSueldosIndexRoute: AuthedSueldosIndexRoute,
  AuthedVencimientosIndexRoute: AuthedVencimientosIndexRoute,
  AuthedClientsClientIdIndexRoute: AuthedClientsClientIdIndexRoute,
  AuthedSueldosProfileIdIndexRoute: AuthedSueldosProfileIdIndexRoute,
  AuthedClientsClientIdProfileIdIndexRoute:
    AuthedClientsClientIdProfileIdIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface ClientRouteRouteChildren {
  ClientPortalIndexRoute: typeof ClientPortalIndexRoute
  ClientPortalSolicitudesIndexRoute: typeof ClientPortalSolicitudesIndexRoute
}

const ClientRouteRouteChildren: ClientRouteRouteChildren = {
  ClientPortalIndexRoute: ClientPortalIndexRoute,
  ClientPortalSolicitudesIndexRoute: ClientPortalSolicitudesIndexRoute,
}

const ClientRouteRouteWithChildren = ClientRouteRoute._addFileChildren(
  ClientRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  ClientRouteRoute: ClientRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  NoOrganizationRoute: NoOrganizationRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiCopilotkitRoute: ApiCopilotkitRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
